### ISSUE TITLE
Support client-requested quality setting

### ISSUE THREAD

**Issue by mdwelsh** [igrigorik/http-client-hints#35]
We'd like to allow clients to specify a "requested quality" (RQ) for web content, as a way of capturing tradeoffs between content quality, size, and time to download.

For example, a client may specifically request degraded content quality as a way of reducing the number of bytes to download or improving page load speed -- for example on slow mobile or satellite networks.

My proposal is to have a small number of discrete settings for RQ, such as "low", "medium", or "high", rather than try to define a continuous spectrum of possible values.

The concept of quality is intentionally meant to be open-ended and sites are welcome to interpret different quality settings in different ways. For example, an RQ of "high" might provide full-resolution images, heavyweight JS to provide rich interaction; while an RQ of "low" might provide lower-resolution images and minimal markup and JS to reduce the page footprint.

Browsers like Chrome and Opera already provide a user setting to request degraded quality content, however this is implemented using proxies to perform content transcoding. Relaying the requested quality to the origin site can allow it to adapt its content explicitly (rather than relying on a proxy that might do bad things to the content), as well as allow SSL-based sites to offer lower-quality content when requested by the client.

**Comment by resrcit-dev** [comment]
I like the quality idea. Bandwidth detection is a very tricky thing, but if anything can do it, its the device itself. I think as devices become more aware of their own connection quality, they are best to decide what resource quality is acceptable.
 
I'd heavily argue the proposed "low", "medium", "high". My point being, what do any of them mean in real 0-100% quality terms; how do they relate to the real world. I know that I personally would much prefer a sliding scale, even if the browser eventually only selects key values along that scale.
For instance, a server delivering an asset receives a "medium", how does that relate to JPEG quality for instance, what quality should the server return? how would we standardise this so all servers behave in the same way and devices know what quality they are going to get? 

Ed

**Comment by yoavweiss** [comment]
> how would we standardise this so all servers behave in the same way and devices know what quality they are going to get?

JPEG quality settings is nothing standard anyway. ("Quality 75" varies wildly between encoders) 
Sending an exact number that mirrors quality would create the illusion of standardization without any real benefits.

**Comment by resrcit-dev** [comment]
Agreed, it will never be perfect because of variance across encoders, but unarguably less by removing the interpretations of Low, Med, High -> 0-100%.

Illusion of standardisation already exists in every encoder people use to save their images, I'm not sure we'd be creating one, more like reenforcing what already exists, granted thats not perfect, but I'd say better than adding another unknown.

**Comment by mdwelsh** [comment]
My concern with supporting fine-grained quality settings is exactly the point that @yoavweiss made - that it's difficult to map these onto meaningful parameters at that level. A coarse-grained set of discrete settings gives sites leeway to interpret them as they wish, with the only provisio that the size or time to download content with a lower quality level should be no greater than that for a higher quality level. The intent here is to convey the user's desire for reduced quality but it's up to sites to actually interpret that signal based on their own content, not to standardize the meaning of the signal across all sites.

**Comment by igrigorik** [comment]
> Bandwidth detection is a very tricky thing, but if anything can do it, its the device itself. I think as devices become more aware of their own connection quality, they are best to decide what resource quality is acceptable.

That particular case is already covered by MD, see: https://www.igvita.com/2014/12/15/capability-reporting-with-service-worker/

> We'd like to allow clients to specify a "requested quality" (RQ) for web content, as a way of capturing tradeoffs between content quality, size, and time to download... My proposal is to have a small number of discrete settings for RQ, such as "low", "medium", or "high", rather than try to define a continuous spectrum of possible values.

@mdwelsh how or why would the proposed RQ hint be different from the "quality" parameter on Accept negotiation [1]? For example, the UA could send a...

```
     Accept: image/webp; q=0.6, image/jpeg; q=0.5, ...
```

The above would indicate that the client is willing to accept either a WebP or JPEG image asset at reduced quality. The same logic can be extended to any content type.. e.g. ship a lightweight experience (JS, CSS, etc) for UAs that advertise the q= parameter on the appropriate content types, etc.

[1] http://tools.ietf.org/html/rfc7231#section-5.3.2

**Comment by resrcit-dev** [comment]
Accept your point about giving developers control over what images they serve, and I'm not necessarily saying that a quality scale NEEDS to map directly onto a JPEG (or other) optimisation scale (however this would simplify handling in many cases). But it is still my opinion that a limited set of options standardised into a header isn't particularly flexible or future proof. 

My ideal would be to see a quality scale (0-100 or 0.00-1.00 etc) in a header interpreted entirely on the server side. This at least means developers are left to interpret values on that scale however they like; with ranges mapping to discrete L,M,H (+more) values, or other developers mapping directly to image quality settings if they chose to do so.

But as per Ilya's post - accept header does seem like a good fit.

Ed

**Comment by yoavweiss** [comment]
I don't think the `q` in `Accept` refers to image quality, but rather to the UA's "preference" for that type of resource. I'm also not sure a 0-100 scale is needed.

All in all, I like the idea of `RQ` as a means for the UA to convey user preferences to the server, and for the server to modify the response accordingly.

**Comment by guypod** [comment]
A couple of thoughts to add here:1) I also don't think we should use the 0-100 scale. Regardless of what we define it as, it'll be  interpreted as a JPEG quality level, which as Ilya said is not standardized. Also, different sites may choose different thresholds for what's low quality (e.g. A high end fashion site may use use JPEG 75 for low and 90 for high, while a corporate site may choose 55 and 75 for those). Lastly, quality scales are non linear and change across image formats and encoders. We need to abstract it. IMO three tiers is sufficient, but we can use more if needs be - just not 100 of them.




2) The only example given so far for motivation for a low quality image was bandwidth estimation. If that's the case, aren't we better off communicating *that*, as opposed to the device's interpretation of the image quality it implies? We're (kinda) already communicating display properties, I can see merit in adding network properties and letting the server (and website owner) decide.




Cheers,

Guypo

**Comment by yoavweiss** [comment]
> 2) The only example given so far for motivation for a low quality image was bandwidth estimation. If that's the case, aren't we better off communicating *that*, as opposed to the device's interpretation of the image quality it implies? We're (kinda) already communicating display properties, I can see merit in adding network properties and letting the server (and website owner) decide.

I'd imagine the main use-case to be user-preferences driven: provide a means to the user to signal the server that they want low quality images (because they're roaming, etc).

Regarding the network, this is already covered by the `MD` hint, which is as close as we can get to provide an accurate BW number. (i.e. by providing the maximum possible one)

**Comment by guypod** [comment]
My point on this still stands - in that case, is the user asking for lower quality images? Or is he stating he’s looking for a fast and low-bandwidth/complexity experience? 

Better communicate the user’s preference, not an interpretation of it.

**Comment by yoavweiss** [comment]
I agree. 

It's probably worth while to run this through some browser UX folks, and see if they think this is something worth exposing.

**Comment by resrcit-dev** [comment]
I don't want to over-complicate, just want something flexible. But 3 tiers are better than none - I'll take that and shut up :+1: 

> I'd imagine the main use-case to be user-preferences driven
As you mentioned, I would be really interested to see how a UX pro would present this to the user. 
Even with Max Downlink, there's still no effective way to measure connection quality automatically.

Ed

**Comment by mdwelsh** [comment]
Agreed with @guypod that the idea here is to represent the users' intent for a lower-quality experience rather than to be overly prescriptive in terms of what specific optimizations/content transformations are performed.

This is something we're actively exploring on the Chrome side as a way of allowing users to opt-in to a lower quality browsing mode, via the existing Reduce Data Usage feature shipped in Chrome Mobile. So as far as browser UX is concerned this is fairly straightforward from our perspective.

The Accept header might work for this, however, it does constrain us to using floating point values between 0.0 to 1.0 as the quality value (cf., http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.9). This would look something like

Accept: */*; q=0.5

However, this could also be interpreted to mean "set JPEG and WebP quality level to 0.5" which is not the same as the "RQ: low" proposed here (which would apply not just to individual resources but possibly to the entire formatting of the page, etc. and not prescribe a specific image quality setting).

**Comment by yoavweiss** [comment]
The Accept header's `q` value is not an indication of image quality, and is already used by browsers to indicate preference for a certain MIME type over others: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

In terms of UX, do you suggest that the values actually used in Chrome would be `RQ: low/medium` (when the user has opted into data savings) and no RQ value at all?

**Comment by mdwelsh** [comment]
@yoavweiss - Right about q not being image quality, but what happens when you specify
    Accept: */*; q=0.5

Wouldn't most servers apply the "q=0.5" to all media types including images? Point is that when we are requesting a low-quality mode that does not necessarily mean serving all individual resources at q=0.5.

Also, yes, the idea is that "RQ: low" when the user has opted into a lo-fi mode in their Reduce Data Usage settings and no RQ would be specified otherwise.

**Comment by yoavweiss** [comment]
> @yoavweiss - Right about q not being image quality, but what happens when you specify
> 
> Accept: */*; q=0.5
> Wouldn't most servers apply the "q=0.5" to all media types including images?

Servers would understand that the UA has no preference with regard to *which* MIME type to send. Nothing about quality. But maybe I'm missing your point here.

Using `Accept` for this has the several disadvantages:
* `q` is already well defined with certain semantics for the last ~15 years. Overriding these semantics needs a good justification, and we'd need to properly think if it won't have compatibility implications with today's Web servers.
* It would further fragment the `Accept` values, which means that `Vary: Accept` would be even less useful than it currently is.
* A server won't be able to vary its responses based on quality alone, since it will get intermixed with the rest of the values in `Accept`

All in all, I think `RQ` would be significantly better than changing the semantics of `Accept`.

**Comment by igrigorik** [comment]
It doesn't matter where we add more entropy... in `Accept` or in a new header, the outcome is the same: more cache variants. That said, there may be an argument that it would be easier for existing caches to deal with a new header as opposed to trying to parse the Accept values... which is why we want Key.

---

Taking a step back, I think we're down into the weeds here. Can we define the use cases and see if we can map them to some existing deployments? From the discussion above:

1. As a user I want to opt-in into an alternate experience (if available):
  1. Data is expensive and I'm willing to accept an experience that consumes less bandwidth.
  1. Latency is high and I'm willing to accept an experience that can deliver faster response times.
1. As a user I want to signal to the site that I want to opt-out from any bandwidth/latency/device/network detection. 
  1. Many sites perform IP/device/network/etc. detection, and force a particular experience on the user. However, there are cases where I want to opt-out and see the "full" experience - e.g. I may be roaming but I still want to fetch high-res images.

Some sites already perform (1) via various heuristics (IP/device/network detection), and we want to allow the user some control over this process. Similarly, (2) affords the user an opt-out strategy if such mechanisms are present and are not desired.

Other use cases?

P.S. How the site goes about optimizing for these cases is completely orthogonal and is deferred to the site.. One site may vary image size or quality, another may strip entire chunks of functionality, and so on.

**Comment by mdwelsh** [comment]
@igrigorik - I think those sound like the right use cases to me. And yes, agreed that this is intended as a signal to sites that they may interpret as they wish.

**Comment by yoavweiss** [comment]
In the spirit of the Extensible Web, it might be a good idea to try to expose these user prefs using a JS API, and then we can look into the best path to expose them towards the server as well.

**Comment by igrigorik** [comment]
@yoavweiss I don't think this needs to be a "browser API". Instead, the application can define own logic around how this is triggered (or set by the user), and use ServiceWorker to append the appropriate headers -- same as [MD example]( https://www.igvita.com/2014/12/15/capability-reporting-with-service-worker/) I shared earlier.

The goal of defining a CH hint for this case would simply be to provide a standardized name + values for interop... assuming we agree on what those should be.

**Comment by yoavweiss** [comment]
@igrigorik The advantage of a Web exposed "User preference" API, is that the browser can provide a unified UI for the user to pick their preference (Just like Chrome does now), and various sites can use that info to influence their various decisions (e.g. by adding a CH header using SW).

**Comment by igrigorik** [comment]
@yoavweiss understood, but I think it's a bit premature at this point. We haven't even agreed on what those settings could/should be. I think the range of the actual options will vary quiet a bit depending on the app, and I'd love to see some examples of this in action plus a clear convergence on some common patterns before talk about a browser API.

**Comment by yoavweiss** [comment]
@igrigorik I totally agree with everything you said. The same is also true for exposing such a preference through CH.

**Comment by mdwelsh** [comment]
There seems to be a chicken-and-egg problem here; if we need "examples of this in action" (which suggests to me an actual implementation) before including this in the CH spec, I don't see how to get browser vendors to implement the spec before it's finalized. The specific use case I have in mind relates to Chrome's "reduce data usage" feature which currently has a single setting - on or off - and does not convey any information to origin sites about when it's been enabled, nor does it send any information to HTTPS sites which they could use to voluntarily degrade quality for the sake of data reduction.

We could start by implementing this in Chrome and adding support to Google services like Search or YouTube to support the header, but absent broad agreement from the browser vendors that this is a good idea such an experiment could end up being a lot of work for nothing. Is that the recommended next step, or can we get some headway in the CH spec before implementing it end-to-end?

I'm not hearing strong objections to the idea at a high level, at least.

**Comment by igrigorik** [comment]
@yoavweiss well, kinda. CH leaves control in developer's hands: they can add the header as they wish and with whatever values they desire.. (e.g via ServiceWorker). Our goal with CH is to (a) spec the hint name, (b) try our best to document reasonable header field values. There is no commitment on API or exact enum of valid values from the platform at this point.. which is what I mean by start with guidance in CH, gather how/if it was implemented, then spec a JS API if necessary...

@mdwelsh my proposal is: 
* Draft CH language for "RQ" (response quality) header field and suggest some values ({high, medium, low}), or some such... We don't need a JS API to start.
* Find sites/developers to experiment with this (e.g. [deploy it via ServiceWorker](https://www.igvita.com/2014/12/15/capability-reporting-with-service-worker/)).
  * Chrome's data compression implementation can adopt it and provide a deeper integration in the settings UI (or whatever mechanism you think is best for this sort of thing).. such that browser emits these headers automatically if the option is set, without relying on a particular site to deploy via the SW route. This also has the added benefit that sites that want to override the Chrome behavior.. can do just that by intercepting the request and providing own value.
* If/when we can show significant traction and adoption of this hint, we can revisit this discussion and consider if it makes sense to also expose a platform JS API to control these hints.

Is that reasonable?

**Comment by mdwelsh** [comment]
@igrigorik - Sounds like a plan. I'm not sure how we would use SW for this, however, since the idea is that this header should be sent when the user has enabled a quality setting in the browser UI. Maybe I'm not following your line of thinking, but from what I can tell using SW does not provide a mechanism to query what is essentially a browser setting (unless that setting were already exposed through a JS API which the SW could call).

**Comment by igrigorik** [comment]
@mdwelsh sorry, poor wording on my part. For Chrome + compression use case you'd need browser-side implementation: user toggles a setting in main UI, Chrome appends appropriate HTTP headers... in other words, exactly as you described. The SW scenario is more of a per-site/app strategy: in my app UI I can surface a setting for similar thing and then have SW intercept and append a header... E.g. YouTube website can surface a setting to toggle video quality and/or other things. Hope that makes sense.

**Comment by igrigorik** [comment]
We had an offline chat with @mdw about this.. Quick summary and proposal for moving forward:

> RQ header field is a [0.0-1.0] number that, in requests, indicates the requested quality of a particular resource. The value is set by the user agent or the application (e.g. via a ServiceWorker, custom header on XHR, etc), and the partitioning and meaning of the communicated value is deferred to the application: this allows the application to define custom semantics without being limited to a fixed number of enum values. For example, an application may partition the range into "low" and "high" by interpreting any value below 0.5 as "low", and define custom ranges for different resources types such as video files, which may partition the 0-1.0 range into more subsets.

* This approach affords the most flexibility and allows developers to define any arbitrary semantics for their particular application and/or resource types. 
* This approach is cache-friendly(er) as it allows range comparisons (e.g. cache and serve and this asset for any request whose advertised RQ value is > 0.3).

Any objections? I'll pull together a spec update next week for this with more coherent language :-)

/cc @mnot

**Comment by atotic** [comment]
Proxies would also want to set this header. Use case is bandwidth-restricted hotspots (remote hotel with satellite wifi). Proxy would insert the header into all outgoing requests.

**Comment by igrigorik** [comment]
@atotic sure, that works just fine. In fact, one of the motivating use cases here is the Chrome Data Compression proxy, which would emit this on outbound requests.

**Comment by igrigorik** [comment]
PTAL at above branch. Thoughts, comments?

At the moment I'm simply defining it as a number between [0-100], the interpretation of which is up to the application + receiving server... But that has the obvious downside that every application has a custom meaning for each value. Should we define some common values / breakpoints - e.g. 0 = low, 50 = med, 100 = high, or some such? It's a tricky one, because I want to allow enough flexibility for sites to define own meaning, but then provide some common interop values.

**Comment by ejthurgo** [comment]
Because it can't easily be ascertained from the image/resource, do you think there is any mileage in returning the provided content quality back to the client via response header, Content-Q (or similar).

Could letting the client identify what quality it has been given on a previous request allow for better caching etc?

**Comment by igrigorik** [comment]
@ejthurgo I think the caching bits are already addressed with Key: http://igrigorik.github.io/http-client-hints/#rfc.section.2.2.2 -- just replace MD examples with RQ.

**Comment by ejthurgo** [comment]
Excellent

**Comment by igrigorik** [comment]
First run at RQ is in new draft: http://igrigorik.github.io/http-client-hints/#the-rq-client-hint

**Comment by mdwelsh** [comment]
Ilya, does your proposal in https://github.com/igrigorik/http-client-hints/pull/39/files allow us to close out this issue?

**Comment by igrigorik** [comment]
Yes, I believe this is resolved now; closing.
