### ISSUE TITLE
update status regarding support from major vendors

### ISSUE THREAD

**Issue by ssbarnea** [igrigorik/http-client-hints#37]
It seems that the status section does miss few essential players: Safari / Apple and Chrome / Google.

I would like to see some information regarding them and maybe even some hints regarding what we can do to persuade them to adopt this.

I found this "project" only now but I was wondering myself why nobody considered using this approach which seems much better than those the do require changing the HTML and CSS code in order to provide support for HiDPI.

**Comment by igrigorik** [comment]
@ssbarnea Blink == Chrome :) ... There is a prototype implementation, but it definitely needs work and I'm hoping that we'll have some good news on that front pretty soon. For Safari, sadly.. I've heard no objections from them, but (sadly), they also typically don't share much in terms of their plans.

p.s. https://github.com/igrigorik/http-client-hints#implementation-status

**Comment by ssbarnea** [comment]
Do you have a WebKit bug on which we can comment? It would be extremely useful if you could provide a list of actions that one supporter could do in order to push this to happen. Like opening a feature request Apple Radar, voting/commenting on issue trackers, forums, lists.

**Comment by igrigorik** [comment]
No webkit bug yet, been focused on Blink/FF. That said.. @yoavweiss have you heard any feedback from Webkit side about CH?

**Comment by yoavweiss** [comment]
Nothing yet, but I'll try to find out.
