### ISSUE TITLE
Less obscure header names

### ISSUE THREAD

**Issue by yoavweiss** [igrigorik/http-client-hints#40]
While discussing the feature on [webkit-dev](https://lists.webkit.org/pipermail/webkit-dev/2015-May/027419.html) concerns were raised with regard to the feature's defined short header names, and the fact that they may be too obscure.

I also heard similar concerns from other people hearing about Client Hints for the first time.

Maybe we should consider longer names?
e.g. DevicePixelRatio, ResourceWidth, MaximumDownlink, ResourceQuality

@igrigorik and @mnot - WDYT?

**Comment by ejthurgo** [comment]
If I recall from early days, people complained about the extra bytes required for 'sensible' header names. In my opinion a moot argument when you put in the context of non-responsive images, but seems you can't keep everyone happy. I for one would welcome descriptive names.

**Comment by igrigorik** [comment]
> (Quoting @mnot from same thread) Regarding the concern about the WG feeling — actually, there's a strong preference for shorter names, as long as it really is something that's going to be on the wire a lot. Roy in particular gets grouchy at long names.

We can't make everyone happy here.. The net-folks like shorter names because uncompressed header bytes do add up pretty quickly. Others may prefer longer and more descriptive names.

FWIW, personally I lean towards shorter names, but if this is a blocking issue, I'm happy to revisit it. Also, if we were to go down that path, I think we'd want hyphenated headers for consistency - e.g. Device-Pixel-Ratio, and so on.

**Comment by yoavweiss** [comment]
Feedback from Mozilla also indicates a preference towards longer, more "user-friendly" header names.

Now all that's left is the bikeshed.
I propose:
`s/RW/Width/`
`s/RQ/Quality/`

I'm not sure if we need to `s/DPR/Device-Pixel-Ratio/` or that `DPR` is a common enough abbreviation.
Regarding `RW` - One point that was raised on the webkit-dev thread was that it may be useful to separate it into `Viewport-Width` and `Resource-Width`. I'll open a separate issue to discuss that.

/cc @marcoscaceres @rniwa

**Comment by mnot** [comment]
Longer headers take more space on the wire in HTTP/1. Width and Quality aren't too bad, but they're horribly prone to being misunderstood - width and quality of *what*? Especially considering that we already have quality values (qvalues). 

Regardless, I wouldn't worry about it too much at this stage; if this does get adopted by the HTTP WG (or any other), this bikeshed will truly be painted gloriously then.

**Comment by igrigorik** [comment]
@mnot we have Blink implementation underway, so that's something we'd like to resolve sooner rather than later.

FWIW, I'm ok with longer names and I think we can find a good balance here - e.g. keep DPR but switch to `Width`.

**Comment by mnot** [comment]
WFM - not talking about saving individual bytes (or even a few), it's just when common (esp.  when they're on every request) header names go crazy that eyebrows get raised...

Cheers,

**Comment by igrigorik** [comment]
Merged https://github.com/igrigorik/http-client-hints/pull/46. 

I'd also like to update "Quality" to something that more closely reflects the intent of indicating that "user has indicated that they want to save data" - e.g. "Data-Saver", or some such. @mdwelsh any thoughts on this one?

**Comment by igrigorik** [comment]
Closing this, let's continue "Quality" discussion in #41.
