### ISSUE TITLE
Use markup info for RW

### ISSUE THREAD

**Issue by yoavweiss** [igrigorik/http-client-hints#41]
Currently `RW` is defined as using the "display width of the requested resource", but it's not well defined where that display width comes from.

Since the browser has no knowledge of the page's layout when it requests images, we've long concluded that the browser should use `sizes` info (or possibly `width`) for that, and fallback to the viewport dimensions when the above is not found. We also concluded that this would be the case even after the page's layout phase in order to avoid raciness.

Can we codify that in some way in the spec? Should that be a note or part of the normative definition of `RW`?

**Comment by igrigorik** [comment]
> Currently RW is defined as using the "display width of the requested resource", but it's not well defined where that display width comes from. 

That's also a feature, since "browser" may not be the only client using this hint. FWIW, I do think it's worth creating a separate "implementation considerations" document which can describe the various design decisions (and discoveries), but I don't think we need to (or should) codify this in the RFC.

**Comment by ejthurgo** [comment]
@yoavweiss Appreciate that the browser has no knowledge of the page's layout when it requests images, but using sizes derived from markup reduces the offering of client hints to little more than a method of communicating DPR (and potentially an optimization preference). As you've documented in your recent amendment, I agree that this (and certainly viewport width), should be considered a fallback.

With limited knowledge of browser architecture, I don't know how technically possible/impossible this would be, but conceptually, I'd like to see a browser implementation delay the requesting of images until the 'actual' size can be effectively determined. I understand that image prefetching is all about improving performance, but on lower bandwidth connections the consequence of delivering images too large with superflous data more than outweighs the marginal gains achieved by prefetching. Although I think initially, this would have to work off some sort of opt-in mechanism. Curious to know your thoughts?

**Comment by igrigorik** [comment]
@ejthurgo fwiw, I think in BW-constrained mode delayed fetching may be reasonable. Specifically, we could delay fetches until we've resolved styles. However, even there, we're not guaranteed to know the resource width - e.g. the page does not specify the container and relies on the image to determine the final layout.

@yoavweiss we've talked about creating a "implementation consideration" section.. let's document this there. Would you be up for taking a first run at this?

**Comment by yoavweiss** [comment]
Yeah, on my todo list. I'll probably get to that once M45 is out the door.

**Comment by igrigorik** [comment]
Closing. Implementation considerations doc: https://github.com/igrigorik/http-client-hints/blob/master/browser_implementation_considerations.md
