### ISSUE TITLE
Relationship between Zoom with DPR and RW

### ISSUE THREAD

**Issue by hexalys** [igrigorik/http-client-hints#44]
Does DPR and RW hints account for browser zoom, or is it a fixed device+screen based value?

**Comment by yoavweiss** [comment]
DPR (like devicePixelRatio) depends on browser zoom and increases as the
user zooms in

**Comment by hexalys** [comment]
Ok. Additionally on desktop will the RW value be relative to the Zoom DPR adjustment then?

**Comment by yoavweiss** [comment]
If the sizes length value is relative to the viewport (e.g. `vw`), since the viewport shrinks when you're zooming in, the `RW` value would shrink, as the `DPR` value increases.

**Comment by hexalys** [comment]
OK thanks. Just wanted to make sure this was the case, for match implementation for an http-client-hints fallback via cookies.
