### ISSUE TITLE
Wrong link target in README.md

### ISSUE THREAD

**Issue by waldbaerkoch** [igrigorik/http-client-hints#57]
In README.md the link 'advertise the Key caching header' in section 'Resource selection' points to
http://igrigorik.github.io/http-client-hints/#rfc.section.2.3.2
which should probably be
http://igrigorik.github.io/http-client-hints/#rfc.section.2.2.2 ('Interaction with Caches')

**Comment by igrigorik** [comment]
Thanks! Fixed in https://github.com/igrigorik/http-client-hints/commit/565e540d9d53681064c6903bf08ceb1dfbedebe4.
