### ISSUE TITLE
Save-Data header is not Clear in the Draft

### ISSUE THREAD

**Issue by vigneshshanmugam** [igrigorik/http-client-hints#60]
Spec states
```
Save-Data = 1

The boolean is a signal indicating explicit user opt-in into a reduced data usage mode on the client, and when communicated to origins allows them to deliver alternate content honoring such preference - e.g. smaller image and video resources, alternate markup, and so on.
```

The term reduced data usage mode on the client conveys more towards enabling the Data Saver mode on Chrome. 

It doesn't convey how other browsers tries to opt-in this feature.

**Comment by igrigorik** [comment]
That's by design. Different browsers offer different ~"data savings" features and IETF (and even W3C) specs do not define the UX of how such things are enabled. The language is intentionally vague.
