### ISSUE TITLE
DPR-based selection/scaling server-side

### ISSUE THREAD

**Issue by waldbaerkoch** [igrigorik/http-client-hints#65]
I am wondering how a DPR-based selection/scaling process would look like server-side, given the following example:
```html
<!-- alternative and equivalent syntax -->
<img src="pic1x.jpg" srcset="pic2x.jpg 2x, pic4x.jpg 4x" alt="A rad wolf.">

<!-- equivalent functionality with DPR hint -->
<img alt="A rad wolf." src="pic.jpg">
```
Selection: If `pic.jpg` is a key that is mapped to `pic1x.jpg 1x, pic2x.jpg 2x, pic4x.jpg 4x` on the server, then with a request containing a `DPR` header the server-side process can select the appropriate URL from the variants given by `pic1x.jpg 1x, pic2x.jpg 2x, pic4x.jpg 4x`. Fine.

Scaling: Unlike the width, which is a property of the image itself, the DPR is sort of a scaling factor and therefore a property of the image's intended use. So, in my opinion, if `pic.jpg` acts as a placeholder for some source image URL, the intended `x` for this source image must also be known, in order to calculate the width of the transformed image suitable for the intended scaling factor given by the `DPR` in the request.
E.g.: The resource width of the source image referenced by `pic.jpg` is 1600 pixels. A request for `pic.jpg` contains the client-hint `DPR: 3` (and **no** `Width` header! That would make it a different use case). What width should a server-side scaling process scale the source image to? This can only be answered if the intended `x` for the source image is known. Let's say this intended `x` is 4. So the process would scale the 1600 pixels wide image to 3 (from `DPR`) / 4 (intended `x` of the source) * 1600 pixels = 1200 pixels.

Any thoughts?

**Comment by igrigorik** [comment]
Yep, you've just outlined the reason for existence of the Content-DPR header. See: http://igrigorik.github.io/http-client-hints/#confirming-selected-dpr

**Comment by waldbaerkoch** [comment]
How? Do you mean the server should not scale, but respond with the 1600 pixel wide source image adding `Content-DPR: 4` and let the client do the scaling when rendering? What about a request with `DPR: 1`? Sending the 1600 pixel wide source image with `Content-DPR: 4` would be a lot of waste.

**Comment by igrigorik** [comment]
No, the server should select the appropriately scaled asset and specify it's DPR via Content-DPR. The client processes the response header and uses it to correctly display the image. Give it a try..
