### ISSUE TITLE
Client hint proposal: `JS`

### ISSUE THREAD

**Issue by wimleers** [igrigorik/http-client-hints#66]
Some functionality only makes sense if the user has JavaScript enabled.

And even sites that are usually rendered on the client side may want to serve a server-side rendered response if it notices the client doesn't have JavaScript.

Hence a boolean `JS` client hint would be quite valuable.

(My concrete use case: Facebook BigPipe-style rendering: https://www.drupal.org/project/big_pipe.)

**Comment by yoavweiss** [comment]
Note that this only makes sense for navigational requests, where we don't have a reasonable opt-in solution.

**Comment by igrigorik** [comment]
Agreed, this is a no-op for CH as we have it defined currently. Also, I'm somewhat skeptical of usefulness.. do you have any telemetry on how often JS is disabled?

**Comment by igrigorik** [comment]
Closing. If you want to reopen, please do so on: https://github.com/httpwg/http-extensions/issues?q=is%3Aopen+is%3Aissue+label%3Aclient-hints (migrating issues there).
