### ISSUE TITLE
Update examples with latest header

### ISSUE THREAD

**Issue by ebidel** [igrigorik/http-client-hints#70]
I noticed the examples in this explainer use separate headers for `DPR` and `Width` and `Viewport-Width`. Is that old?

Shouldn't they be using `Accept-CH`, with those as values?

**Comment by igrigorik** [comment]
No, that should be correct..

- Accept-CH is the header server sends to advertise what headers it wants client to send
- Client sends individual headers with relevant values enabled by Accept-CH

Does that make sense?

**Comment by ebidel** [comment]
Yea, makes perfect sense. I thinkp part of my confusion was that the client can do the opt-in:

`<meta http-equiv="Accept-CH" content="Viewport-Width">`
